"""Unit tests for Quick Switcher dynamic candidate rendering (§A3).

Proves that:
1. Quick Switcher candidate list updates dynamically when DB fixture contains a different agent/contact set.
2. Contains ZERO literal occurrences of 'Code Scout', 'Data Cleaner', 'Bob', 'Priya'.
"""

from pathlib import Path

import pytest
import yaml

from kin.cli import open_profile_db
from kin.storage.db import create_schema
from kin.tui.app import KinApp


def test_quick_switcher_dynamic_candidates_no_demo_literals(tmp_path: Path):
    """Assert Quick Switcher candidates change dynamically with fixture DB and zero demo literals (§A3)."""
    prof_dir = tmp_path / "profiles" / "switcher_user"
    agents_dir = prof_dir / "agents"
    agents_dir.mkdir(parents=True, exist_ok=True)
    db_path = prof_dir / "kin.db"

    # 1. Custom agent card matching schema & filename stem
    card_yaml = {
        "schema_version": "1.1",
        "id": "custom-agent-99",
        "name": "Custom Security Scanner",
        "description": "Scans codebase for secrets",
        "adapter": {"type": "local_command", "command": "echo scan", "working_directory": str(tmp_path.resolve())},
        "capabilities": {"tags": ["security"], "accepts": ["text/plain"], "produces": ["text/plain"]},
        "boundaries": {"filesystem": "workspace_read", "shell": "deny", "max_runtime_seconds": 300, "max_artifact_bytes": 1048576},
        "autonomy": {"relay_information": "always_ask", "propose_actions": "always_ask", "execute_local_actions": "always_ask"},
    }
    (agents_dir / "custom-agent-99.yaml").write_text(yaml.dump(card_yaml), encoding="utf-8")

    # 2. Custom contact
    conn = open_profile_db(db_path)
    create_schema(conn)
    conn.execute(
        "INSERT INTO contacts (username, display_name, public_key, x25519_public_key, endpoint, autonomy_level, fingerprint_verified_at) VALUES ('dave', 'Dave Architect', 'pk_dave', 'xpk_dave', 'http://127.0.0.1:8100', 'always_ask', '2026-07-31T00:00:00Z')"
    )
    conn.commit()
    conn.close()

    app = KinApp(profile_name="switcher_user", profile_dir=prof_dir)

    # Collect candidates generated by action_action_quick_switcher logic
    from kin.tui.local_state import get_all_agent_summaries, get_local_contacts_summaries

    local_agents, peer_agents = get_all_agent_summaries(prof_dir, "switcher_user")
    contacts = get_local_contacts_summaries(prof_dir, "switcher_user")

    agent_names = [a.name for a in local_agents + peer_agents]
    contact_names = [c.display_name or c.username for c in contacts]

    assert "Custom Security Scanner" in agent_names
    assert "Dave Architect" in contact_names

    # Invariants: Hardcoded demo literals MUST NOT be present
    all_rendered_titles = agent_names + contact_names
    assert "Code Scout" not in all_rendered_titles
    assert "Data Cleaner" not in all_rendered_titles
    assert "Bob" not in all_rendered_titles
    assert "Priya" not in all_rendered_titles
